/*
 * Nativize Migration Hub — plan + command generator.
 *
 * Turns a scan result (from migration-scanner.js) into:
 *   • ordered copyable command groups for the "Run Migration" step
 *   • four downloadable markdown files
 *   • guided-mode checklists for non-Supabase targets
 *
 * SAFETY: every generated command uses <placeholders> for secret values.
 * A Supabase project ref is a public identifier so it may be inlined;
 * keys, passwords, and tokens never are.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.NativizeMigrationPlan = factory();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  function ref(inputs) {
    var r = String((inputs && inputs.projectRef) || "").trim();
    return /^[a-z0-9]{18,24}$/.test(r) ? r : "<target-project-ref>";
  }
  function today() { return new Date().toISOString().slice(0, 10); }

  /* ================= Step 4: ordered copyable commands ================= */
  function commandGroups(scan, inputs) {
    var R = ref(inputs);
    var fnNames = scan.edgeFunctions.map(function (f) { return f.name; }).filter(function (name) { return /^[A-Za-z0-9_-]{1,120}$/.test(name); });
    var groups = [];

    groups.push({
      title: "1 · Back up first",
      desc: "One branch and one ZIP — your rollback plan before anything else runs.",
      commands: [
        { label: "Create a backup branch", cmd: "git checkout -b backup-before-migration-" + today() + " && git push -u origin backup-before-migration-" + today() },
        { label: "Safe ZIP (never includes .env, .git, node_modules)", cmd: 'zip -r ../project-backup-' + today() + '.zip . -x "*.env" -x ".env*" -x "*/.env*" -x ".git/*" -x "node_modules/*" -x "*/node_modules/*"' }
      ]
    });

    groups.push({
      title: "2 · Link the target Supabase project",
      desc: "Log in locally, then point the CLI at your NEW project. Never link a live production project you don't intend to change.",
      commands: [
        { label: "Log in to the Supabase CLI", cmd: "supabase login" },
        { label: "Link the target project", cmd: "supabase link --project-ref " + R }
      ]
    });

    groups.push({
      title: "3 · Push the database",
      desc: scan.sqlMigrations.length + " SQL migration file" + (scan.sqlMigrations.length === 1 ? "" : "s") + " will be applied to the target in order.",
      commands: [
        { label: "Apply every migration to the target", cmd: "supabase db push" }
      ]
    });

    if (fnNames.length) {
      var batch = "#!/usr/bin/env bash\nset -euo pipefail\n" + fnNames.map(function (n) { return "supabase functions deploy " + n; }).join("\n");
      groups.push({
        title: "4 · Deploy edge functions",
        desc: fnNames.length + " function" + (fnNames.length === 1 ? "" : "s") + " detected under supabase/functions/.",
        commands: [
          { label: "Deploy all functions (batch script — save as deploy-functions.sh)", cmd: batch }
        ].concat(fnNames.map(function (n) {
          return { label: "Deploy only " + n, cmd: "supabase functions deploy " + n, advanced: true };
        }))
      });
    }

    if (scan.secrets.length) {
      var serverSecrets = scan.secrets.filter(function (s) { return s.scope !== "frontend" && /^[A-Z0-9_]{1,80}$/.test(s.name); });
      groups.push({
        title: (fnNames.length ? "5" : "4") + " · Set secrets (placeholders only)",
        desc: "Replace each <value> locally before running. Values never touch Nativize.",
        commands: serverSecrets.map(function (s) {
          return { label: s.name, cmd: "supabase secrets set " + s.name + "=<value>" };
        })
      });
    }

    groups.push({
      title: "· Rebuild and verify",
      desc: "Install, build, and hunt down any old project refs left behind.",
      commands: [
        { label: "Install dependencies", cmd: "npm install" },
        { label: "Production build", cmd: "npm run build" },
        { label: "Lint / typecheck (if the project has it)", cmd: "npm run lint --if-present && npm run typecheck --if-present", advanced: true },
        { label: "Find old Supabase project refs", cmd: 'grep -rn --exclude-dir=node_modules --exclude-dir=.git -E "' + (scan.projectRefs.filter(function (r) { return /^[a-z0-9]{18,24}$/.test(r); }).join("|") || "[a-z0-9]{20}\\.supabase\\.co") + '" .', advanced: !scan.projectRefs.length }
      ]
    });

    return groups;
  }

  /* ================= Markdown files ================= */
  function h(fnName) { return "`" + fnName + "`"; }
  function checkbox(items) { return items.map(function (i) { return "- [ ] " + i; }).join("\n"); }

  function planMarkdown(scan, inputs) {
    var R = ref(inputs);
    var lines = [];
    lines.push("# Manual Supabase Migration Plan");
    lines.push("");
    lines.push("_Generated by Nativize App Migration on " + today() + ". No secret values appear in this file — placeholders only._");
    lines.push("");
    lines.push("**Project size:** " + scan.sqlMigrations.length + " SQL migrations · " + scan.edgeFunctions.length + " edge functions · " + scan.storageBuckets.length + " storage buckets · " + scan.secrets.length + " secret names detected.");
    lines.push("");
    lines.push("## 1. Backup checklist");
    lines.push(checkbox([
      "Create a backup branch: `git checkout -b backup-before-migration-" + today() + "`",
      "Push the backup branch to your remote",
      "Export a safe ZIP excluding `.env*`, `.git`, `node_modules`",
      "If the source database is reachable, take a dump: `supabase db dump -f backup.sql`"
    ]));
    lines.push("");
    lines.push("## 2. Source export checklist");
    lines.push(checkbox([
      "Confirm `supabase/migrations/` is complete (" + scan.sqlMigrations.length + " files found)",
      "Confirm `supabase/functions/` is complete (" + scan.edgeFunctions.length + " functions found)",
      scan.hasConfigToml ? "Review `supabase/config.toml` for auth redirect URLs and site_url" : "No `supabase/config.toml` found — note target auth settings manually",
      scan.envFiles.length ? "⚠ REMOVE the .env file(s) from the export and rotate any keys inside: " + scan.envFiles.map(function (e) { return "`" + e.path + "`"; }).join(", ") : "No .env files in the export — good"
    ]));
    lines.push("");
    lines.push("## 3. Target Supabase project checklist");
    lines.push(checkbox([
      "Create a CLEAN target project (never reuse a live one)",
      "Note the project ref: `" + R + "`",
      "Do NOT paste the service role key into any web tool — the CLI reads it locally after `supabase login`"
    ]));
    lines.push("");
    lines.push("## 4. Database migration");
    lines.push(checkbox([
      "`supabase login`",
      "`supabase link --project-ref " + R + "`",
      "`supabase db push` (applies all " + scan.sqlMigrations.length + " migrations in order)",
      "Verify tables + RLS policies in the dashboard"
    ]));
    lines.push("");
    lines.push("## 5. Storage buckets");
    lines.push(scan.storageBuckets.length
      ? checkbox(scan.storageBuckets.map(function (b) { return "Create bucket `" + b + "` on the target (match public/private setting), then copy objects"; }))
      : "_No storage bucket references detected._");
    lines.push("");
    lines.push("## 6. Edge functions");
    lines.push(scan.edgeFunctions.length
      ? checkbox(scan.edgeFunctions.map(function (f) { return "Deploy " + h(f.name) + ": `supabase functions deploy " + f.name + "`" + (f.usesServiceRole ? " (uses service role key — set automatically by Supabase)" : ""); }))
      : "_No edge functions detected._");
    lines.push("");
    lines.push("## 7. Secrets setup");
    lines.push(scan.secrets.length
      ? checkbox(scan.secrets.filter(function (s) { return s.scope !== "frontend"; }).map(function (s) { return "`supabase secrets set " + s.name + "=<value>`"; }))
      : "_No server secrets detected._");
    lines.push("");
    lines.push("## 8. Auth providers");
    lines.push(checkbox([
      "Re-configure each OAuth provider (Google, Apple, GitHub…) on the target project",
      "Set Site URL and redirect URLs" + (scan.authRedirects.length ? " (redirect usage found in: " + scan.authRedirects.slice(0, 5).map(function (p) { return "`" + p + "`"; }).join(", ") + ")" : ""),
      scan.deepLinks.length ? "Re-register deep link schemes: " + scan.deepLinks.map(function (d) { return "`" + d + "://`"; }).join(", ") : "No custom deep link schemes detected"
    ]));
    lines.push("");
    lines.push("## 9. Payments / webhooks");
    var pay = scan.integrations.filter(function (i) { return ["revenuecat", "stripe", "webhooks"].indexOf(i.id) > -1; });
    lines.push(pay.length
      ? checkbox(pay.map(function (i) { return "Update " + i.label + " endpoint URLs to point at the target project (seen in " + i.files.slice(0, 3).map(function (f) { return "`" + f + "`"; }).join(", ") + ")"; }))
      : "_No payment/webhook integrations detected._");
    lines.push("");
    lines.push("## 10. Domains / DNS / deep links");
    lines.push(checkbox([
      "Update production domain env vars and redirect URLs",
      "Update Apple universal links / Android app links if you ship native apps",
      "Verify HTTPS on the final domain"
    ]));
    lines.push("");
    lines.push("## 11. Final testing");
    lines.push("See `POST_MIGRATION_TEST_CHECKLIST.md` — do not switch traffic until required tests pass.");
    lines.push("");
    lines.push("## 12. Rollback plan");
    lines.push(checkbox([
      "Keep the source project untouched until all tests pass",
      "Rollback = point the app back at the source project ref + keys",
      "Your backup branch `backup-before-migration-" + today() + "` restores the exact pre-migration code"
    ]));
    lines.push("");
    lines.push("> Never drop the `auth` schema. Never delete storage objects via SQL. Review every destructive command before running it.");
    return lines.join("\n");
  }

  function secretsMarkdown(scan) {
    var lines = ["# Supabase Secrets Checklist", "", "_Names only — values never leave your machine. Set each one locally with the Supabase CLI._", ""];
    if (!scan.secrets.length) { lines.push("_No secret names detected._"); return lines.join("\n"); }
    scan.secrets.forEach(function (s) {
      lines.push("## `" + s.name + "`");
      lines.push("- Used in: " + s.files.map(function (f) { return "`" + f + "`"; }).join(", "));
      lines.push("- Scope: " + (s.scope === "frontend" ? "frontend/public (bundled into the app — must be safe to expose)" : "server-only (edge function secret)"));
      if (s.scope !== "frontend") lines.push("- Set it: `supabase secrets set " + s.name + "=<value>`");
      else lines.push("- Set it in your build env (e.g. `.env.local`, never committed): `" + s.name + "=<value>`");
      if (s.suspicious) lines.push("- ⚠ **WARNING:** this name looks like a private secret but appears in frontend code. Move it server-side and rotate the value.");
      lines.push("");
    });
    return lines.join("\n");
  }

  function deployMarkdown(scan) {
    var lines = ["# Supabase Function Deploy Commands", "", "_One section per function under `supabase/functions/`._", ""];
    if (!scan.edgeFunctions.length) { lines.push("_No edge functions detected._"); return lines.join("\n"); }
    scan.edgeFunctions.forEach(function (f) {
      lines.push("## `" + f.name + "`");
      lines.push("```sh");
      lines.push("supabase functions deploy " + f.name);
      lines.push("```");
      lines.push("- Secrets used: " + (f.secrets.length ? f.secrets.map(function (s) { return "`" + s + "`"; }).join(", ") : "none detected"));
      lines.push("- Has `deno.json`: " + (f.hasDenoJson ? "yes" : "no"));
      lines.push("- Imports `_shared`: " + (f.importsShared ? "yes — deploy keeps shared code automatically" : "no"));
      lines.push("- Likely uses service role key: " + (f.usesServiceRole ? "yes (provided automatically by Supabase at runtime)" : "no"));
      lines.push("- External APIs referenced: " + (f.externalApis.length ? f.externalApis.join(", ") : "none detected"));
      if (f.secrets.length && !f.hasEnvErrorHandling) lines.push("- ⚠ No missing-env error handling detected — the function may fail silently if a secret is unset.");
      lines.push("");
    });
    return lines.join("\n");
  }

  function testMarkdown(scan) {
    var has = function (id) { return scan.integrations.some(function (i) { return i.id === id; }); };
    var items = [
      "App builds cleanly (`npm run build`)",
      "Supabase connection works (app loads live data)",
      "Signup / login (email)",
      "Profile loading"
    ];
    if (scan.authRedirects.length || scan.hasConfigToml) { items.push("Google login", "Apple login", "Auth email links point at the new project"); }
    items.push("User preferences persist");
    if (scan.storageBuckets.length) { items.push("Storage uploads work (buckets: " + scan.storageBuckets.join(", ") + ")", "Storage reads/downloads work"); }
    scan.edgeFunctions.forEach(function (f) { items.push("Edge function `" + f.name + "` responds correctly"); });
    if (has("stripe")) items.push("Stripe checkout + webhook fire against the new project");
    if (has("revenuecat")) items.push("RevenueCat webhook points at the new project and validates");
    if (has("youtube")) items.push("YouTube API calls succeed");
    if (has("soundcloud")) items.push("SoundCloud proxy/playback works");
    if (has("audius")) items.push("Audius proxy works");
    if (has("deezer")) items.push("Deezer metadata loads");
    if (has("lastfm")) items.push("Last.fm recommendations load");
    if (has("ai")) items.push("Gemini/OpenAI calls succeed with new secrets");
    if (has("family")) items.push("Family invite / accept flow works end-to-end");
    if (has("email")) items.push("Transactional/support emails send");
    if (has("cron")) items.push("Cron jobs are re-scheduled on the target and fire");
    if (has("push")) items.push("Push notifications deliver");
    if (scan.deepLinks.length) items.push("iOS deep links open the app (" + scan.deepLinks.join(", ") + ")", "Android deep links open the app");
    items.push("Production domain redirects and HTTPS");
    var lines = ["# Post-Migration Test Checklist", "", "_Do not switch your backend until every required test passes._", "", checkbox(items), "", "## Ready to switch?", checkbox(["All required tests above pass", "Rollback plan confirmed (source project untouched)", "Team/users notified if downtime is possible"])];
    return lines.join("\n");
  }

  /* ================= Guided-mode checklists for other targets ================= */
  function guidedChecklist(targetId, scan) {
    var sections = [];
    function sec(title, items) { sections.push({ title: title, items: items }); }
    if (targetId === "aws") {
      sec("Architecture", ["Pick the shape: S3 + CloudFront (frontend), RDS Postgres (database), Lambda + API Gateway (functions)", "Draw the request path before creating anything"]);
      sec("S3 storage", ["Create a private bucket per storage need (" + (scan.storageBuckets.join(", ") || "none detected") + ")", "Serve public assets via CloudFront, not public buckets"]);
      sec("RDS / Postgres", ["Create RDS Postgres 15+ in a private subnet", "Restore schema: apply your `supabase/migrations/*.sql` in order with `psql`", "Note: Supabase-specific extensions/schemas (auth, storage) will not exist — replace with Cognito or your own auth"]);
      sec("Lambda / API Gateway", scan.edgeFunctions.length ? scan.edgeFunctions.map(function (f) { return "Port edge function `" + f.name + "` to a Lambda handler (Deno → Node/Deno layer)"; }) : ["No edge functions detected"]);
      sec("Environment variables", scan.secrets.filter(function (s) { return s.scope !== "frontend"; }).map(function (s) { return "Store `" + s.name + "` in SSM Parameter Store / Secrets Manager"; }));
      sec("Domain / DNS", ["Route 53 or your registrar → CloudFront", "ACM certificate for HTTPS"]);
      sec("Deployment", ["Frontend: `npm run build` → `aws s3 sync dist/ s3://<bucket>`", "Invalidate CloudFront after deploys"]);
      sec("Cost warnings", ["Set an AWS Budget alert BEFORE deploying", "RDS is billed hourly even when idle — stop dev instances"]);
      sec("Security", ["Scoped IAM deploy user (no root keys)", "Security groups: DB reachable only from Lambda/app subnet", "Enable CloudTrail"]);
    } else if (targetId === "firebase") {
      sec("Firestore / Auth", ["Model your SQL tables as collections (denormalize joins)", "Enable matching sign-in providers in Firebase Auth"]);
      sec("Storage", (scan.storageBuckets.length ? scan.storageBuckets.map(function (b) { return "Recreate bucket `" + b + "` as a Storage path + rules"; }) : ["No buckets detected"]));
      sec("Functions", scan.edgeFunctions.length ? scan.edgeFunctions.map(function (f) { return "Port `" + f.name + "` to a Cloud Function (Deno → Node)"; }) : ["No edge functions detected"]);
      sec("Env / secrets", scan.secrets.filter(function (s) { return s.scope !== "frontend"; }).map(function (s) { return "`firebase functions:secrets:set " + s.name + "`"; }));
      sec("Web app config", ["Add the Firebase web config to your app (public by design)", "Remove Supabase client code paths"]);
      sec("Deployment", ["`firebase init` → `firebase deploy`", "Set up preview channels for testing"]);
    } else if (targetId === "vercel") {
      sec("Build settings", ["Framework preset auto-detects Vite/Next", "Confirm `npm run build` output directory"]);
      sec("Environment variables", scan.secrets.map(function (s) { return "Add `" + s.name + "` (" + (s.scope === "frontend" ? "expose to browser" : "server-only") + ") in Project → Settings → Environment Variables"; }));
      sec("Domains", ["Add your domain, update DNS, verify HTTPS", "Keep your backend (Supabase/Neon) URLs pointing at the target project"]);
    } else if (targetId === "neon" || targetId === "postgres") {
      sec("Database", ["Create the target database", "Apply migrations in order: `psql \"<connection-string>\" -f supabase/migrations/<file>.sql` (or concatenate)", "Note: Supabase `auth`/`storage` schemas need replacements — this target is data-only"]);
      sec("App wiring", ["Set `DATABASE_URL=<connection-string>` in your app host's secret store", "Remove Supabase client auth calls or keep Supabase for auth only"]);
    } else if (targetId === "docker") {
      sec("Compose stack", ["Write docker-compose.yml: app + postgres:16 + reverse proxy (Caddy/Traefik for auto-HTTPS)", "Volumes for Postgres data + uploads"]);
      sec("Database", ["Apply `supabase/migrations/*.sql` with `psql` inside the container", "Schedule `pg_dump` backups (cron) off-server"]);
      sec("Env / secrets", scan.secrets.filter(function (s) { return s.scope !== "frontend"; }).map(function (s) { return "`" + s.name + "=<value>` in the server's .env (chmod 600, never committed)"; }));
      sec("Security", ["Do not publish the Postgres port publicly", "Enable UFW/firewall; SSH keys only"]);
    } else if (targetId === "github-export") {
      sec("Before the first push", ["Confirm `.gitignore` covers `.env*`, `node_modules`, build output", scan.envFiles.length ? "⚠ Remove detected .env files first: " + scan.envFiles.map(function (e) { return e.path; }).join(", ") : "No .env files detected — good"]);
      sec("Push", ["`git init && git add -A && git commit -m 'Import'`", "`git remote add origin git@github.com:<owner>/<repo>.git && git push -u origin main`"]);
      sec("Secrets", ["Add CI secrets in repo Settings → Secrets and variables"]);
    } else if (targetId === "nativize") {
      sec("Native conversion", ["Open Nativize Studio (/app/) with this repo", "Pick platforms + options; Studio generates the Capacitor project into your repo", "Cloud builds produce installable apps — iOS needs no Mac"]);
    }
    return sections;
  }

  return {
    commandGroups: commandGroups,
    planMarkdown: planMarkdown,
    secretsMarkdown: secretsMarkdown,
    deployMarkdown: deployMarkdown,
    testMarkdown: testMarkdown,
    guidedChecklist: guidedChecklist,
    FILES: [
      { name: "MANUAL_SUPABASE_MIGRATION_PLAN.md", fn: "planMarkdown" },
      { name: "SUPABASE_SECRETS_CHECKLIST.md", fn: "secretsMarkdown" },
      { name: "SUPABASE_FUNCTION_DEPLOY_COMMANDS.md", fn: "deployMarkdown" },
      { name: "POST_MIGRATION_TEST_CHECKLIST.md", fn: "testMarkdown" }
    ]
  };
});
