/* Nativize Migration Hub — browser-only scan + server-enforced entitlements. */
(function () {
  "use strict";

  var root = document.getElementById("migrationApp");
  var Billing = window.NativizeBilling;
  var Providers = window.NativizeMigrationProviders;
  var Scanner = window.NativizeMigrationScanner;
  var Plan = window.NativizeMigrationPlan;
  if (!root || !Billing || !Providers || !Scanner || !Plan) return;

  var K = {
    access: "nz_web_supabase_access",
    refresh: "nz_web_supabase_refresh",
    verifier: "nz_migration_pkce_verifier",
    draft: "nz_migration_draft",
    pending: "nz_migration_pending_action"
  };
  var accessToken = sessionStorage.getItem(K.access) || "";
  var refreshToken = sessionStorage.getItem(K.refresh) || "";
  var accessState = null;
  var busy = false;

  function esc(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  function jsonLoad(key, fallback) { try { return JSON.parse(sessionStorage.getItem(key)) || fallback; } catch (_) { return fallback; } }
  function jsonSave(key, value) { try { sessionStorage.setItem(key, JSON.stringify(value)); } catch (_) {} }
  function localLoad(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch (_) { return fallback; } }
  function localSave(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch (_) {} }
  function slugName(filename) { return String(filename || "My app").replace(/\.zip$/i, "").replace(/[-_]+/g, " ").trim().slice(0, 80) || "My app"; }
  function statusBadge(provider) { var s = Providers.statusOf(provider); return '<span class="mh-status ' + s.id + '">' + esc(s.label) + "</span>"; }
  function toast(message) { var old = document.querySelector(".mh-toast"); if (old) old.remove(); var el = document.createElement("div"); el.className = "mh-toast"; el.textContent = message; document.body.appendChild(el); setTimeout(function () { el.remove(); }, 2200); }
  function setAccount() { var b = document.getElementById("mhAccount"); if (!b) return; b.textContent = accessToken ? "Signed in" : "Sign in"; b.onclick = function () { if (accessToken) toast("Your secure session is active in this browser tab."); else signIn(); }; }
  function clearAuthParams() { var u = new URL(location.href); var changed = !!u.hash; u.hash = ""; ["code","access_token","refresh_token","provider_token","expires_at","expires_in","token_type","state","error","error_description"].forEach(function (k) { if (u.searchParams.has(k)) { u.searchParams.delete(k); changed = true; } }); if (changed) history.replaceState(null, "", u.pathname + (u.search ? u.search : "")); }
  function saveTokens(tokens) { accessToken = tokens.accessToken || ""; refreshToken = tokens.refreshToken || refreshToken || ""; if (accessToken) sessionStorage.setItem(K.access, accessToken); if (refreshToken) sessionStorage.setItem(K.refresh, refreshToken); setAccount(); }
  function renew() { return Billing.refreshSession(refreshToken).then(function (tokens) { saveTokens(tokens); return tokens; }); }
  function api(method, args) { args = args || []; return Billing[method].apply(Billing, [accessToken].concat(args)).catch(function (err) { if (!refreshToken || !err || (err.status !== 401 && err.status !== 403)) throw err; return renew().then(function () { return Billing[method].apply(Billing, [accessToken].concat(args)); }); }); }
  function signIn(pending) { if (pending) sessionStorage.setItem(K.pending, pending); return Billing.createPkce().then(function (pkce) { sessionStorage.setItem(K.verifier, pkce.codeVerifier); location.href = Billing.authorizeUrl(location.href.split("#")[0], { codeChallenge: pkce.codeChallenge, codeChallengeMethod: pkce.codeChallengeMethod }); }); }
  function handleAuth() { var tokens = Billing.parseAuthTokens(location.href); if (tokens.error) { clearAuthParams(); return Promise.reject(new Error(tokens.error)); } if (!tokens.code) return Promise.resolve(); var verifier = sessionStorage.getItem(K.verifier) || ""; if (!verifier) { clearAuthParams(); return Promise.reject(new Error("Sign-in security check failed. Start again.")); } return Billing.exchangeCodeForSession(tokens.code, verifier).then(function (session) { sessionStorage.removeItem(K.verifier); if (!session.accessToken) throw new Error("Sign-in did not return a session."); saveTokens(session); clearAuthParams(); }); }
  function currentUrl(params) { var u = new URL(location.href); u.hash = ""; u.search = ""; Object.keys(params || {}).forEach(function (k) { u.searchParams.set(k, params[k]); }); return u.toString(); }
  function checkout(planId) { if (!accessToken) return signIn("checkout:" + planId); busy = true; renderWizard(); return api("checkout", [planId, { successUrl: currentUrl({ checkout: "success" }), cancelUrl: currentUrl({ checkout: "cancelled" }) }]).then(function (res) { location.href = res.url; }).catch(function (err) { busy = false; renderWizard(err.message); }); }

  var steps = ["Connect", "Target", "Scan", "Run", "Test"];
  function progress(active) { return '<div class="mh-progress">' + steps.map(function (s, i) { var cls = i < active ? "done" : i === active ? "active" : ""; return '<div class="mh-progress-item ' + cls + '"><b>' + (i < active ? "✓ " : "") + s + "</b><span>Step " + (i + 1) + "</span></div>"; }).join("") + "</div>"; }
  function appHead(title, sub, active) { return '<div class="mh-app-head"><div><span class="mh-badge">5 guided steps</span><h1>' + esc(title) + '</h1><p>' + esc(sub) + '</p></div><span class="mh-kicker">No raw secrets stored</span></div>' + progress(active); }
  function defaultDraft() { return { step: 0, source: "lovable", target: "supabase", filename: "", name: "", scan: null, size: null, risk: null, targetInputs: {}, anonChecked: false, projectId: null }; }
  var draft = Object.assign(defaultDraft(), jsonLoad(K.draft, {}));
  function saveDraft() { jsonSave(K.draft, draft); }
  function providerCard(p, selected) { return '<article class="mh-card mh-choice ' + (selected ? "selected " : "") + (p.status === "soon" ? "disabled" : "") + '" data-provider="' + esc(p.id) + '"><div class="top"><span class="ico">' + p.icon + "</span>" + statusBadge(p) + "</div><h3>" + esc(p.name) + "</h3><p>" + esc(p.blurb) + "</p></article>"; }
  function panel(title, sub, body, actions) { return '<section class="mh-panel"><div class="mh-panel-head"><div><h2>' + esc(title) + "</h2><p>" + esc(sub) + "</p></div></div>" + body + '<div class="mh-panel-actions">' + actions + "</div></section>"; }
  function stat(label, value, cls) { return '<div class="mh-stat"><b class="' + (cls || "") + '">' + esc(value) + "</b><span>" + esc(label) + "</span></div>"; }

  function renderConnect(error) {
    var sources = Providers.SOURCES.map(function (p) { return providerCard(p, draft.source === p.id); }).join("");
    var scan = draft.scan;
    var upload = '<div class="mh-upload"><b>' + (scan ? "✓ Project scanned locally" : "Add your project ZIP") + '</b><p style="color:var(--mh-muted);font-size:13px">The file never leaves this browser. Only redacted scan metadata can be saved after you unlock a project.</p><input id="mhZip" type="file" accept=".zip,application/zip"><div id="mhScanStatus" style="margin-top:12px;color:var(--mh-muted);font-size:13px">' + (scan ? esc(draft.filename + " · " + scan.fileCount + " files") : "") + "</div></div>";
    var body = (error ? '<div class="mh-error">' + esc(error) + "</div>" : "") + '<div class="mh-choice-grid">' + sources + "</div>" + upload + '<div class="mh-note">GitHub connection is available in Nativize Studio. For this launch workflow, downloading the repo as ZIP gives the full local scan without sending source code to Nativize.</div>';
    return panel("Connect Source", "Choose where the project came from, then scan an exported ZIP.", body, '<a class="mh-btn" href="/migration/">Cancel</a><button class="mh-btn primary" id="mhNext" ' + (!scan ? "disabled" : "") + ">Choose target →</button>");
  }

  function targetFields(target) {
    if (target.id === "supabase") return '<div class="mh-form"><div class="mh-field"><label>Target Supabase project URL</label><input id="mhProjectUrl" type="url" placeholder="https://YOUR-REF.supabase.co" value="' + esc(draft.targetInputs.projectUrl || "") + '"><small>A clean target project is recommended.</small></div><div class="mh-field"><label>Target project ref</label><input id="mhProjectRef" maxlength="24" placeholder="20-character project ref" value="' + esc(draft.targetInputs.projectRef || "") + '"><small>Public project identifier, not a secret.</small></div><div class="mh-field"><label>Publishable / anon key (optional check)</label><input id="mhAnonKey" type="password" autocomplete="off" placeholder="Checked locally, never saved"><small>This value is validated in memory and immediately discarded. Never enter a service role key.</small></div></div><div class="mh-note warn">Never paste a service role key. Nativize does not need it, does not store it, and does not generate commands containing it.</div>';
    var inputs = target.inputs || [];
    if (!inputs.length) return '<div class="mh-note">No credentials are needed here. Guided Mode will create a platform-specific checklist from your scan.</div>';
    return '<div class="mh-form">' + inputs.map(function (f) { return '<div class="mh-field"><label>' + esc(f.label) + '</label><input data-target-input="' + esc(f.key) + '" placeholder="' + esc(f.placeholder || "") + '" value="' + esc(draft.targetInputs[f.key] || "") + '"><small>Configuration only — never enter a password or private token.</small></div>'; }).join("") + "</div>";
  }
  function renderTarget(error) { var targets = Providers.TARGETS.map(function (p) { return providerCard(p, draft.target === p.id); }).join(""); var target = Providers.target(draft.target) || Providers.target("supabase"); var body = (error ? '<div class="mh-error">' + esc(error) + '</div>' : "") + '<div class="mh-choice-grid">' + targets + '</div><div style="margin-top:24px"><h3>Target details</h3>' + targetFields(target) + '</div>'; return panel("Choose Target", "Supabase is fully supported. Other available targets use honest Guided Mode.", body, '<button class="mh-btn" id="mhBack">← Connect</button><button class="mh-btn primary" id="mhNext">Scan &amp; plan →</button>'); }

  function accessBox() {
    if (!accessToken) return '<div class="mh-paywall"><h3>Preview complete. Sign in to continue.</h3><p>Full migration projects are included with Max or use one Single Migration credit.</p><div class="mh-actions"><button class="mh-btn primary" data-action="signin">Sign in with GitHub</button></div><div class="mh-trust-row"><span>No raw secrets stored</span><span>You stay in control</span></div></div>';
    if (accessState && accessState.access === "max") return '<div class="mh-paywall"><h3>Included with Max</h3><p>Your Max entitlement is verified on the server. Creating this project will not use a migration credit.</p><div class="mh-actions"><button class="mh-btn primary" data-action="create">Create full migration project →</button></div></div>';
    if (accessState && accessState.access === "credit") return '<div class="mh-paywall"><h3>One migration credit available</h3><p>Creating the project will use one credit and attach it permanently to this migration. You will confirm before it is consumed.</p><div class="mh-actions"><button class="mh-btn primary" data-action="create">Use one credit &amp; continue →</button></div></div>';
    return '<div class="mh-paywall"><h3>Unlock the full 5-step workflow</h3><p>Included with Max, or buy one migration. You receive the full command workflow, generated markdown files, secrets checklist, and testing dashboard.</p><div class="mh-actions"><button class="mh-btn primary" data-action="checkout-max">Choose Max</button><button class="mh-btn" data-action="checkout-migration">Buy one migration</button><button class="mh-btn" data-action="refresh-access">I already paid — refresh</button></div><div class="mh-trust-row"><span>Safe commands and checklists</span><span>No raw secrets stored</span><span>You stay in control</span></div></div>';
  }
  function scanCards(scan, riskOverride) { var risk = riskOverride || draft.risk || Scanner.riskOf(scan); return '<div class="mh-stats">' + stat("SQL files", scan.sqlMigrations.length) + stat("Edge functions", scan.edgeFunctions.length) + stat("Storage buckets", scan.storageBuckets.length) + stat("Secret names", scan.secrets.length) + stat("Risk", risk.label, "mh-risk " + risk.level) + "</div>"; }
  function renderScan(error) { var s = draft.scan; if (!s) { draft.step = 0; saveDraft(); return renderConnect("Scan data is missing. Add the ZIP again."); } var warnings = s.warnings.length ? '<div class="mh-list">' + s.warnings.map(function (w) { return '<div class="mh-list-row"><strong class="mh-risk ' + esc(w.level) + '">' + (w.level === "danger" ? "Danger" : "Needs attention") + "</strong>" + esc(w.text) + "</div>"; }).join("") + "</div>" : '<div class="mh-note">No immediate secret or project-ref risks were found. Review the generated plan before running commands.</div>'; var integrations = s.integrations.length ? s.integrations.map(function (i) { return '<span class="mh-badge">' + esc(i.label) + "</span>"; }).join(" ") : '<span style="color:var(--mh-muted)">No external integrations detected.</span>'; var body = (error ? '<div class="mh-error">' + esc(error) + "</div>" : "") + scanCards(s) + '<div class="mh-grid" style="margin:20px 0"><article class="mh-card"><h3>Database</h3><p>' + s.sqlMigrations.length + " migration files · " + (s.hasConfigToml ? "config.toml found" : "no config.toml") + '</p></article><article class="mh-card"><h3>Functions &amp; secrets</h3><p>' + s.edgeFunctions.length + " functions · " + s.secrets.length + ' secret names · values discarded</p></article><article class="mh-card"><h3>Detected services</h3><p>' + integrations + "</p></article></div><h3>Warnings and recommended actions</h3>" + warnings + '<div class="mh-note">Generated for the supported Supabase path: migration plan, secrets checklist, function deploy commands, and post-migration test checklist.</div>' + accessBox(); return panel("Scan & Plan", "Review the local preview before creating a paid migration project.", body, '<button class="mh-btn" id="mhBack">← Target</button><span style="color:var(--mh-muted);font-size:12px">' + esc(draft.size || "small") + " project · " + esc((draft.risk || {}).label || "Safe") + "</span>"); }

  function renderWizard(error) {
    root.innerHTML = appHead("New migration", "Move an AI-built app without giving up control.", draft.step) + (busy ? '<section class="mh-panel"><div class="mh-loading">Preparing your secure migration project…</div></section>' : draft.step === 0 ? renderConnect(error) : draft.step === 1 ? renderTarget(error) : renderScan(error));
    bindWizard();
  }
  function bindChoices(kind) { document.querySelectorAll("[data-provider]").forEach(function (el) { el.onclick = function () { var p = kind === "source" ? Providers.source(el.dataset.provider) : Providers.target(el.dataset.provider); if (!p || p.status === "soon") { toast("That provider is coming soon."); return; } if (kind === "source") draft.source = p.id; else { draft.target = p.id; draft.targetInputs = {}; draft.anonChecked = false; } saveDraft(); renderWizard(); }; }); }
  function validateTarget() {
    var target = Providers.target(draft.target);
    if (!target || target.status === "soon") throw new Error("Choose an available target.");
    if (target.id === "supabase") {
      var url = (document.getElementById("mhProjectUrl").value || "").trim();
      var ref = (document.getElementById("mhProjectRef").value || "").trim().toLowerCase();
      var anon = (document.getElementById("mhAnonKey").value || "").trim();
      if (!/^https:\/\/[a-z0-9]{18,24}\.supabase\.co\/?$/i.test(url)) throw new Error("Enter a valid target Supabase project URL.");
      if (!/^[a-z0-9]{18,24}$/.test(ref)) throw new Error("Enter the 18–24 character target project ref.");
      if (url.toLowerCase().indexOf(ref + ".supabase.co") < 0) throw new Error("The target URL and project ref do not match.");
      if (/sb_secret_|service.?role/i.test(anon)) throw new Error("That looks like a service role / secret key. Remove it immediately and rotate it if it was exposed.");
      draft.targetInputs = { projectUrl: url, projectRef: ref };
      draft.anonChecked = !!anon;
      if (anon) document.getElementById("mhAnonKey").value = "";
    } else {
      var values = {};
      document.querySelectorAll("[data-target-input]").forEach(function (el) { var v = (el.value || "").trim(); if (/secret|password|token|private.?key/i.test(v) || Scanner.looksLikeSecretValue(v)) throw new Error("A target field looks like a private credential. Remove it; Migration Hub only accepts non-secret configuration."); values[el.dataset.targetInput] = v.slice(0, 200); });
      draft.targetInputs = values;
    }
  }
  function loadAccess() { if (!accessToken) { accessState = null; renderWizard(); return Promise.resolve(); } return api("migrationAccess").then(function (v) { accessState = Array.isArray(v) ? v[0] : v; renderWizard(); }).catch(function (e) { renderWizard("Could not verify Migration Hub access: " + e.message); }); }
  function generatedFiles() { if (draft.target !== "supabase") return []; return [{ name: Plan.FILES[0].name, content: Plan.planMarkdown(draft.scan, draft.targetInputs) },{ name: Plan.FILES[1].name, content: Plan.secretsMarkdown(draft.scan) },{ name: Plan.FILES[2].name, content: Plan.deployMarkdown(draft.scan) },{ name: Plan.FILES[3].name, content: Plan.testMarkdown(draft.scan) }]; }
  function createProject() {
    if (busy) return;
    if (!accessState || accessState.access === "none") { loadAccess(); return; }
    if (accessState.access === "credit" && !confirm("This will use your one migration credit and attach it to this project. Continue?")) return;
    busy = true; renderWizard();
    var params = { name: (draft.name || slugName(draft.filename)) + " migration", source: draft.source, target: draft.target, targetProjectRef: draft.targetInputs.projectRef || null };
    api("createMigrationProject", [params]).then(function (created) {
      created = Array.isArray(created) ? created[0] : created;
      draft.projectId = created.id; saveDraft();
      return api("saveMigrationScan", [created.id, draft.scan, draft.size, draft.risk.level]).then(function () { var files = generatedFiles(); return files.length ? api("saveMigrationFiles", [created.id, files]) : null; }).then(function () { return created; });
    }).then(function (created) { location.href = "/migration/" + created.id + "/commands"; }).catch(function (err) { busy = false; var extra = draft.projectId ? " Your project was created and your credit is safely attached; reopen it at /migration/" + draft.projectId + "." : " No credit was consumed if project creation failed."; renderWizard(err.message + extra); });
  }
  function bindWizard() {
    if (draft.step === 0) {
      bindChoices("source"); var zip = document.getElementById("mhZip"); if (zip) zip.onchange = function () { var file = zip.files && zip.files[0]; if (!file) return; if (!/\.zip$/i.test(file.name)) { renderWizard("Choose a .zip project export."); return; } if (file.size > 120 * 1024 * 1024) { renderWizard("ZIP is over 120 MB. Exclude node_modules, build output, and .git, then try again."); return; } var st = document.getElementById("mhScanStatus"); st.textContent = "Scanning locally…"; zip.disabled = true; file.arrayBuffer().then(Scanner.unzip).then(function (files) { var result = Scanner.scan(files); if (!Scanner.isSupabaseStyle(result) && draft.source === "lovable") result.warnings.push({ level: "warn", text: "This does not look like a Lovable/Supabase project. You can continue, but the Supabase plan may be limited." }); draft.scan = result; draft.filename = file.name.slice(0, 180); draft.name = slugName(file.name); draft.size = Scanner.sizeOf(result); draft.risk = Scanner.riskOf(result); saveDraft(); renderWizard(); }).catch(function (e) { renderWizard("Could not scan this ZIP: " + e.message); }); };
      var n0 = document.getElementById("mhNext"); if (n0) n0.onclick = function () { draft.step = 1; saveDraft(); renderWizard(); };
    } else if (draft.step === 1) {
      bindChoices("target"); document.getElementById("mhBack").onclick = function () { draft.step = 0; saveDraft(); renderWizard(); }; document.getElementById("mhNext").onclick = function () { try { validateTarget(); draft.step = 2; saveDraft(); renderWizard(); loadAccess(); } catch (e) { renderWizard(e.message); } };
    } else {
      var back = document.getElementById("mhBack"); if (back) back.onclick = function () { draft.step = 1; saveDraft(); renderWizard(); };
      document.querySelectorAll("[data-action]").forEach(function (el) { el.onclick = function () { var a = el.dataset.action; if (a === "signin") signIn(); else if (a === "checkout-max") checkout("max"); else if (a === "checkout-migration") checkout("migration"); else if (a === "refresh-access") loadAccess(); else if (a === "create") createProject(); }; });
    }
  }

  function projectRoute() { var m = location.pathname.match(/^\/migration\/([0-9a-f-]{36})(?:\/(secrets|commands|testing))?\/?$/i); if (m) return { id: m[1], tab: m[2] || "overview" }; var q = new URLSearchParams(location.search); var id = q.get("id"); return id && /^[0-9a-f-]{36}$/i.test(id) ? { id: id, tab: q.get("tab") || "overview" } : null; }
  function projectNav(route, project) { var base = "/migration/" + route.id; var links = [{ id: "overview", href: base, label: "Overview" },{ id: "secrets", href: base + "/secrets", label: "Secrets checklist" },{ id: "commands", href: base + "/commands", label: "Commands" },{ id: "testing", href: base + "/testing", label: "Testing" }]; return '<aside class="mh-side">' + links.map(function (l) { return '<a class="mh-card ' + (route.tab === l.id ? "active" : "") + '" href="' + l.href + '"><h3>' + l.label + "</h3><p>" + (l.id === "overview" ? "Scan and next actions" : l.id === "secrets" ? "Names only, never values" : l.id === "commands" ? "Copy. Run. Check." : "Verify before switching") + "</p></a>"; }).join("") + '<a class="mh-btn" href="/migration/new/">+ New migration</a></aside>'; }
  function projectProgress(project, tab) { var map = { connect: 0, target: 1, scan: 2, run: 3, test: 4, done: 5 }; var n = map[project.status] == null ? 2 : map[project.status]; if (tab === "commands") n = Math.max(n, 3); if (tab === "testing") n = Math.max(n, 4); return progress(Math.min(n, 4)); }
  function summaryPanel(project, scan) { var computed = Scanner.riskOf(scan); var risk = project.risk ? { level: project.risk, label: project.risk === "danger" ? "Danger" : project.risk === "warn" ? "Needs attention" : "Safe" } : computed; var warnings = scan.warnings && scan.warnings.length ? '<div class="mh-list" style="margin-top:16px">' + scan.warnings.map(function (w) { return '<div class="mh-list-row"><strong class="mh-risk ' + esc(w.level) + '">' + (w.level === "danger" ? "Danger" : "Needs attention") + "</strong>" + esc(w.text) + "</div>"; }).join("") + "</div>" : '<div class="mh-note">No stored warning text. Review detected refs, env-file flags, and secrets before continuing.</div>'; return '<section class="mh-panel"><div class="mh-panel-head"><div><h2>Scan summary</h2><p>Saved metadata is redacted. No source files or secret values are stored.</p></div><span class="mh-status ' + (project.target_provider === "supabase" ? "full" : "guided") + '">' + (project.target_provider === "supabase" ? "Fully supported" : "Guided mode") + "</span></div>" + scanCards(scan, risk) + warnings + "</section>"; }
  function filesPanel(files) { if (!files.length) return ""; return '<section class="mh-panel" style="margin-top:18px"><div class="mh-panel-head"><div><h2>Generated files</h2><p>Copy or download the real markdown plan.</p></div></div><div class="mh-files">' + files.map(function (f) { return '<article class="mh-card mh-file"><h3>' + esc(f.name) + "</h3><p>" + esc((f.content || "").slice(0, 150).replace(/[#_*`]/g, "")) + '…</p><div class="mh-actions"><button class="mh-btn mh-copy-file" data-file="' + esc(f.name) + '">Copy</button><button class="mh-btn mh-download-file" data-file="' + esc(f.name) + '">Download</button></div></article>'; }).join("") + "</div></section>"; }
  function renderOverview(data) { var p = data.project, scan = data.scan.summary; var target = Providers.target(p.target_provider); return summaryPanel(p, scan) + '<section class="mh-panel" style="margin-top:18px"><div class="mh-panel-head"><div><h2>Recommended next actions</h2><p>' + esc(target ? target.blurb : "Review the generated plan.") + '</p></div></div><div class="mh-list"><div class="mh-list-row"><strong>1 · Review secrets</strong>Confirm every detected name has a safe destination. Never paste values into this site.</div><div class="mh-list-row"><strong>2 · Run commands locally</strong>Start with the backup branch and safe ZIP, then link only the intended target.</div><div class="mh-list-row"><strong>3 · Complete every required test</strong>The dashboard will not mark this migration done until the checklist is complete.</div></div><div class="mh-panel-actions"><a class="mh-btn" href="/migration/' + p.id + '/secrets">Review secrets</a><a class="mh-btn primary" href="/migration/' + p.id + '/commands">Open commands →</a></div></section>' + filesPanel(data.files); }
  function renderCommands(data) { var p = data.project, scan = data.scan.summary; if (p.target_provider !== "supabase") { var sections = Plan.guidedChecklist(p.target_provider, scan); return '<section class="mh-panel"><div class="mh-panel-head"><div><h2>' + esc((Providers.target(p.target_provider) || {}).name || p.target_provider) + ' Guided Mode</h2><p>Platform-specific guidance; no deployment automation is claimed.</p></div><span class="mh-status guided">Guided mode</span></div>' + sections.map(function (s) { return '<details class="mh-card" style="margin:10px 0" open><summary><b>' + esc(s.title) + '</b></summary><div class="mh-list" style="margin-top:12px">' + s.items.map(function (i) { return '<div class="mh-list-row">' + esc(i) + '</div>'; }).join("") + "</div></details>"; }).join("") + '<div class="mh-panel-actions"><a class="mh-btn" href="/migration/' + p.id + '">Overview</a><a class="mh-btn primary" href="/migration/' + p.id + '/testing">Continue to testing →</a></div></section>'; }
    var groups = Plan.commandGroups(scan, { projectRef: p.target_project_ref }); return '<section class="mh-panel"><div class="mh-panel-head"><div><h2>Copy. Run. Check.</h2><p>Run these locally, in order. Commands contain placeholders only.</p></div><span class="mh-status full">Fully supported</span></div><div class="mh-note danger">Review the linked target before every database command. Never run reset, wipe, or drop commands on production.</div>' + groups.map(function (g, gi) { var normal = g.commands.filter(function (c) { return !c.advanced; }); var advanced = g.commands.filter(function (c) { return c.advanced; }); return '<div style="margin-top:24px"><h3>' + esc(g.title) + '</h3><p style="color:var(--mh-muted);font-size:13px">' + esc(g.desc) + "</p>" + normal.map(commandHtml).join("") + (advanced.length ? '<details><summary style="cursor:pointer;color:var(--mh-muted);font-size:13px">Advanced commands</summary>' + advanced.map(commandHtml).join("") + "</details>" : "") + "</div>"; }).join("") + '<div class="mh-panel-actions"><a class="mh-btn" href="/migration/' + p.id + '/secrets">← Secrets</a><button class="mh-btn primary" id="mhCommandsDone">I ran and checked these →</button></div></section>'; }
  function commandHtml(c) { return '<div class="mh-command"><div class="mh-command-head"><span>' + esc(c.label) + '</span><button class="mh-btn mh-copy" data-copy-command>Copy</button></div><pre>' + esc(c.cmd) + "</pre></div>"; }
  function renderSecrets(data) { var p = data.project, scan = data.scan.summary; return '<section class="mh-panel"><div class="mh-panel-head"><div><h2>Secrets checklist</h2><p>Only environment variable names and usage locations were saved.</p></div><span class="mh-kicker">Values never stored</span></div><div class="mh-note danger">If you uploaded a .env file or pasted a private key anywhere, remove it and rotate the affected credential before continuing.</div><div class="mh-list" style="margin-top:18px">' + (scan.secrets.length ? scan.secrets.map(function (s) { return '<div class="mh-list-row"><strong>' + esc(s.name) + (s.suspicious ? ' <span class="mh-risk danger">· move server-side</span>' : "") + '</strong>' + esc(s.scope) + " · " + esc((s.files || []).join(", ")) + (s.scope !== "frontend" ? '<div class="mh-command"><div class="mh-command-head"><span>Placeholder only</span><button class="mh-btn mh-copy" data-copy="supabase secrets set ' + esc(s.name) + '=&lt;value&gt;">Copy</button></div><pre>supabase secrets set ' + esc(s.name) + '=&lt;value&gt;</pre></div>' : "") + "</div>"; }).join("") : '<div class="mh-empty">No secret names were detected.</div>') + '</div><div class="mh-panel-actions"><a class="mh-btn" href="/migration/' + p.id + '">← Overview</a><a class="mh-btn primary" href="/migration/' + p.id + '/commands">Open commands →</a></div></section>'; }
  function renderTesting(data) { var p = data.project, scan = data.scan.summary; var markdown = Plan.testMarkdown(scan); var items = markdown.split("\n").filter(function (l) { return /^- \[ \] /.test(l); }).map(function (l) { return l.slice(6); }); var key = "nz_migration_tests_" + p.id; var checked = localLoad(key, []); return '<section class="mh-panel"><div class="mh-panel-head"><div><h2>Test &amp; Switch</h2><p>Do not switch the backend until every required test is checked.</p></div><span class="mh-status ' + (p.status === "done" ? "full" : "guided") + '">' + (p.status === "done" ? "Checklist complete" : "Testing") + '</span></div><div id="mhTestList">' + items.map(function (item, i) { return '<label class="mh-check"><input type="checkbox" data-test-index="' + i + '" ' + (checked.indexOf(i) > -1 ? "checked" : "") + '><span>' + esc(item) + '</span></label>'; }).join("") + '</div><div class="mh-note">“Ready” records that your checklist passed. The actual backend switch remains manual and under your control.</div><div class="mh-panel-actions"><a class="mh-btn" href="/migration/' + p.id + '/commands">← Commands</a><button class="mh-btn primary" id="mhReady" ' + (checked.length < items.length || !items.length ? "disabled" : "") + '>Ready to switch backend</button></div></section>'; }

  var currentData = null;
  function downloadText(name, text) { var blob = new Blob([text], { type: "text/markdown;charset=utf-8" }); var u = URL.createObjectURL(blob); var a = document.createElement("a"); a.href = u; a.download = name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(function () { URL.revokeObjectURL(u); }, 500); }
  function bindProject(route, data) {
    document.querySelectorAll("[data-copy-command]").forEach(function (b) { b.onclick = function () { navigator.clipboard.writeText(b.closest(".mh-command").querySelector("pre").textContent).then(function () { toast("Command copied"); }); }; });
    document.querySelectorAll("[data-copy]").forEach(function (b) { b.onclick = function () { navigator.clipboard.writeText(b.dataset.copy).then(function () { toast("Placeholder command copied"); }); }; });
    document.querySelectorAll(".mh-copy-file").forEach(function (b) { b.onclick = function () { var f = data.files.find(function (x) { return x.name === b.dataset.file; }); if (f) navigator.clipboard.writeText(f.content).then(function () { toast("File copied"); }); }; });
    document.querySelectorAll(".mh-download-file").forEach(function (b) { b.onclick = function () { var f = data.files.find(function (x) { return x.name === b.dataset.file; }); if (f) downloadText(f.name, f.content); }; });
    var done = document.getElementById("mhCommandsDone"); if (done) done.onclick = function () { done.disabled = true; api("updateMigrationStatus", [route.id, "test"]).then(function () { location.href = "/migration/" + route.id + "/testing"; }).catch(function (e) { toast(e.message); done.disabled = false; }); };
    var boxes = Array.prototype.slice.call(document.querySelectorAll("[data-test-index]")); var ready = document.getElementById("mhReady"); boxes.forEach(function (box) { box.onchange = function () { var ids = boxes.filter(function (x) { return x.checked; }).map(function (x) { return Number(x.dataset.testIndex); }); localSave("nz_migration_tests_" + route.id, ids); if (ready) ready.disabled = ids.length !== boxes.length; }; });
    if (ready) ready.onclick = function () { if (!boxes.length || boxes.some(function (x) { return !x.checked; })) return; if (!confirm("Record every required test as complete? This does not change production automatically; you still control the backend switch.")) return; ready.disabled = true; api("updateMigrationStatus", [route.id, "done"]).then(function () { toast("Checklist complete — switch remains in your control"); setTimeout(function () { location.reload(); }, 700); }).catch(function (e) { toast(e.message); ready.disabled = false; }); };
  }
  function renderProjectData(route, data) { currentData = data; var p = data.project, scan = data.scan && data.scan.summary; if (!p || !scan) { root.innerHTML = appHead("Migration project", "Private project data", 2) + '<div class="mh-error">This project is missing its scan. Reopen the new-migration flow or contact support.</div>'; return; } var target = Providers.target(p.target_provider); var content = route.tab === "secrets" ? renderSecrets(data) : route.tab === "commands" ? renderCommands(data) : route.tab === "testing" ? renderTesting(data) : renderOverview(data); root.innerHTML = '<div class="mh-app-head"><div><span class="mh-badge">' + esc((Providers.source(p.source_provider) || {}).name || p.source_provider) + ' → ' + esc(target ? target.name : p.target_provider) + '</span><h1>' + esc(p.name) + '</h1><p>Created ' + esc(new Date(p.created_at).toLocaleDateString()) + ' · ' + esc(p.size || Scanner.sizeOf(scan)) + ' project</p></div><span class="mh-kicker">You stay in control</span></div>' + projectProgress(p, route.tab) + '<div class="mh-two"><div>' + content + '</div>' + projectNav(route, p) + '</div>'; bindProject(route, data); }
  function renderProjectsList(projects) { root.innerHTML = appHead("Your migrations", "Private projects visible only to your account.", 0) + '<section class="mh-panel"><div class="mh-panel-actions" style="margin-top:0;padding-top:0;border:0"><span>' + projects.length + ' project' + (projects.length === 1 ? "" : "s") + '</span><a class="mh-btn primary" href="/migration/new/">New migration</a></div><div class="mh-list" style="margin-top:18px">' + (projects.length ? projects.map(function (p) { return '<a class="mh-list-row" style="color:inherit;text-decoration:none" href="/migration/' + p.id + '"><strong>' + esc(p.name) + "</strong>" + esc(p.source_provider) + " → " + esc(p.target_provider) + " · " + esc(p.status) + "</a>"; }).join("") : '<div class="mh-empty">No migration projects yet.</div>') + "</div></section>"; }
  function initProject() { if (!accessToken) { root.innerHTML = appHead("Your migration project", "Sign in to load private scan data.", 0) + '<section class="mh-panel"><div class="mh-empty"><p>This route is protected by server-side row security.</p><button class="mh-btn primary" id="mhProjectSignin">Sign in with GitHub</button></div></section>'; document.getElementById("mhProjectSignin").onclick = function () { signIn(); }; return; } var route = projectRoute(); if (!route) { api("listMigrationProjects").then(renderProjectsList).catch(function (e) { root.innerHTML = '<div class="mh-error">' + esc(e.message) + "</div>"; }); return; } api("getMigrationProject", [route.id]).then(function (data) { if (!data.project) throw new Error("Project not found or it belongs to another account."); var next = route.tab === "commands" && data.project.status === "scan" ? "run" : route.tab === "testing" && ["scan","run"].indexOf(data.project.status) > -1 ? "test" : null; if (!next) return data; return api("updateMigrationStatus", [route.id, next]).then(function (result) { result = Array.isArray(result) ? result[0] : result; data.project.status = result.status || next; return data; }); }).then(function (data) { renderProjectData(route, data); }).catch(function (e) { root.innerHTML = appHead("Migration project", "Private project data", 0) + '<div class="mh-error">' + esc(e.message) + "</div>"; }); }

  handleAuth().then(function () {
    setAccount();
    var pending = sessionStorage.getItem(K.pending); sessionStorage.removeItem(K.pending);
    if (pending && pending.indexOf("checkout:") === 0) { checkout(pending.split(":")[1]); return; }
    if (root.dataset.view === "project") initProject(); else { var checkoutState = new URLSearchParams(location.search).get("checkout"); renderWizard(checkoutState === "success" ? "Payment received. Refresh access if the credit is still processing." : checkoutState === "cancelled" ? "Checkout was cancelled; your preview is still here." : null); if (draft.step === 2) loadAccess(); }
  }).catch(function (e) { setAccount(); if (root.dataset.view === "project") root.innerHTML = '<div class="mh-error">' + esc(e.message) + "</div>"; else renderWizard(e.message); });
})();
